### PR TITLE
Finale touches

### PR DESCRIPTION
**Pull request by joskalenda**
# Mabills tracker application 

> Mabills tracker enables you to monitor how much of your budget has been spent over time, to see how much is remaining, and course-correct when necessary.

## Interactions

- [ ] Splash screen ✅ 

1. Sign up and login pages

- The user should be able to register in the app with his full name, email and password (all mandatory).
- The user can log into the app using email and password.
- If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
   

- [ ]  Home page (catagories page) ✅ 

1. When the user logs in, they are presented with the categories page.
2. For each category, the user can see their name, icon, and the total amount of all the transactions that belongs to that category.
3. When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
4. There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- [ ] Transactions page ✅ 

1. The list of transactions is presented, ordered by the most recent for a given category.
2. At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
3. There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
4. When the user clicks on the "Back" button (<), the user navigates to the home page.

- [ ] Add a new category page ✅ 

1. The user fills out a form to create a new category, indicating their name and icon (both mandatory).
2. The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
3. When the user clicks on the "Back" button (<), the user navigates to the home page.

- [ ] "Add a new transaction" page ✅ 

1. The user fills out a form to create a new transaction with:
2. name (mandatory)
3. amount (mandatory)
4. categories (mandatory at least one)
5. The user click (or taps) the "Save" button to create the new category, and is taken to the transactions page for that category.
6. When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

- [ ] Testing cases ✅ 

|         Rspec and capybara            |   
:--------------------------------:|
test |

- [ ] The project should be deployed and accessible [online](https://mabills-tracker.herokuapp.com/) ✅

### CODE REVIEW

**Review by ahmetbozaci — CHANGES_REQUESTED** [review]
# STATUS: Changes Required  ♻️


 @joskalenda  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Nice to have 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
- I can add categories and transactions without error. ✔️
- Nice to deploy the project to Heroku.✔️
- I can't log in if ı can try login unexist user and ı can see a flash message on the page.✔️
- I can see the list of transactions is presented ordered by the most recent I can see the total amount. ✔️


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._
- [ ] _I can't give inline comments because you already merged codes. Please next time doesn't merge it before review._
- [ ] Nice to add some flash messages but ı can see 3 messages after signup or 2 messages after adding transaction. Please fix it.
image
image
- [ ] You should add creative common license in the readme in the license section. [Requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=The%20Creative%20Commons%20license%20of%20the%20design%20requires%20that%20you%20give%20appropriate%20credit%20to%20the%20author.%20Therefore%2C%20you%20must%20do%20it%20in%20the%20README%20of%20your%20project.)
- [ ]  Please fix broken link in the mıt license.
___
- [ ] Nice to create presentation video and show the demo but you should also show some codes that you proud of it. [Requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=you%20should%20also%20highlight%20some%20interesting%20piece%20of%20code%20or%20something%20you%20built%20that%20you%20are%20very%20proud%20of.)
- [ ] You should use `only` keyword if you wont some routes. Please update it.
image
- [ ] You should follow the design guidelines. Design should be exactly same(color, typography, layout). Please update your design. [Requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Project%20requirements-,Design,will%20create%20them%20following%20the%20design%20guidelines%20of%20the%20other%20pages.,-Original%20design%20idea)
image
image
image
image
___
### ORIGINAL
image



### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
almost

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by joskalenda** [comment]
Hello @ahmetbozaci, thanks for giving this review, I would like to mention a few things I couldn't get well on your suggest changes, the design layout, and colors, I think I use the same as per this picture, you can check it out or maybe you could be more detailed on what and what I should update
new

- I have updated the notice message, thanks for mentioning that 😄 

- for my routes file, why do you think I should use the only keyword? is it a part of the requirement? my routes are correctly working so am not sure to understand.
thanks in advance

**Comment by ahmetbozaci** [comment]
> Hello @ahmetbozaci, thanks for giving this review, I would like to mention a few things I couldn't get well on your suggest changes, the design layout, and colors, I think I use the same as per this picture, you can check it out or maybe you could be more detailed on what and what I should update new
> 
> * I have updated the notice message, thanks for mentioning that smile
> * for my routes file, why do you think I should use the only keyword? is it a part of the requirement? my routes are correctly working so am not sure to understand.
>   thanks in advance
 

- [ ] Hello  @joskalenda . Not only the blue color you should follow all design guidelines. Like in the design picture you can see the button color is different, background color of the page is different. The example you can see in the picture form is on the navbar.
image

Please compare what is different(layout, font family, font size, color, spaces of element) and make sure ıt will be the same. It is part of the requirement.

- [ ] Yes, your routes working perfectly. But according to the requirement, you should use only keywords and it is good for practice. Check this [article](https://jaryl.medium.com/disciplined-rails-models-controllers-the-rails-way-bbc940822136) why you should use only keywords.

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾✔🎉**
Hello @joskalenda 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by joskalenda** [comment]
@emmanuellekamwa, thank you

**Pull request merged**
